### ISSUE TITLE
Dedicated followed hashtags overview

### ISSUE THREAD

**Issue by pacorob** [Decad3nce/trunks-public#63] opened 2023-02-10 11:01 UTC
I would love to be able to see an overview of all my followed hashtags and be able to press them to see their timelines. 
A combination of multiple followed hashtags would even be cooler. 

If the overview of followed hashtags could also become available via the (iOS) footer e.g. long press on federated/local to switch / left hand (iPadOS) to select the overview of followed hashtags and then select an individual hashtag.

**Comment by Decad3nce** [comment] 2023-02-11 07:10
Duplicate of #30

**Closed by Decad3nce** 2023-02-11 07:10 UTC
